### ISSUE TITLE
Plan out the "rooms" feature.

### ISSUE THREAD

**Issue by austinpray** [UTD-CRSS/app.exploreapollo.org#13]
We will arbitrarily define combinations of channels and their points of interest and make them navigable as "rooms". Think of it like a chat room with a specific topic. 

In this thread let's discuss how this should be implemented. Things like:

* url structure
* how does the user find a room?
* what filters are available?
* search?

**Comment by JamieCrisman** [comment]
I'd maybe call them conversations? maybe moments? 

I don't feel like rooms makes much sense in the metaphor...? 

### URL

If we're storing them in the database we can just get the moment by an id from the database.
`exploreapollo.org/#/moment/{momentid}`
`exploreapollo.org/#/moment/313374`

if we do database method we could do more user friendly ids as well. 
`exploreapollo.org/#/moment/oneSmallStep` could just be an alias to `exploreapollo.org/#/moment/313374`


if not we're going to have to do some snazzy encoding. my initial thoughts are some sort of encoded string and having a timestamp
`exploreapollo.org/#/moment/{encodedString}/{timestamp}`
`exploreapollo.org/#/moment/aEaad/3d4h20m11s`

encodedString:
binary toggle to choose active channels.
For an example we can do have channels 2, 6, 7 active in 8 channels,  `0110 0010 => 6 2` There's tons of different ways we can encode it (binary to hex?) so it'll have all the information the url. 

timestamp:
tons of ways we can do this too.. we can read in a timestamp 1d4h20m10s (think youtube does this format? it's more user friendly) or we can just do some int for an offset.

I might even suggest having a mix of the two? so the second one with the encoding would allow people to share moments and the first one would be our own curations (within the database?)

### Finding rooms

Weren't these going to be pointed out on the timeline?
It'd be cool if you don't have the same channels active at the time, the timeline will somehow notify you an event is coming up soon. We need to have some way to show the user that if they're listening to specific channels at some time, they might not hear something interesting being said on other channels.

I think it'd be nice to have an inbetween on what soundcloud does and how polymer elements do pins/comments on a 'timeline'
<img width="853" alt="screen shot 2015-09-23 at 7 26 57 pm" src="https://cloud.githubusercontent.com/assets/697955/10062566/6b4b9b72-6229-11e5-9fed-962922cd362b.png">

<img width="946" alt="screen shot 2015-09-23 at 7 28 20 pm" src="https://cloud.githubusercontent.com/assets/697955/10062580/9a33d0b2-6229-11e5-9303-1a2330169fc9.png">
 so here instead of having a 20, we can have some sort of message or allow you to click it to change rooms/moments. Maybe have the pin be a little more discreet when it's not close, but you can hover over?

### search

This... is something that will be pretty tricky to do... Obviously depending on how much text we get, but transcript search is something we can do... but there can be a lot. if we're doing multiple timelines... I'd say have a search bar on each one. Access via a search button? (I don't like the idea of multiple timelines for growing complexities like this)

for finding rooms/conversations of interest/moments my thoughts are trying to find tags or keywords for certain events? this would be another +1 on having our own curated events in a db...

### filters
This goes back to tagging the conversations/room/moment some how. Maybe we can have tag subscriptions. While the users listen to the channels it'll switch to conversations that have a tag that the user is subscribed to. (tricky if they're overlapping conversations though) or allow them to jump to conversations from a particular person they're subscribed to?

A lot of this is just brain storming. We'll want to narrow these down.

**Comment by austinpray** [comment]
## Regarding Naming

I agree "rooms" is weak.

- I don't like "moments" because this "room" concept is essentially a collection of moments.
- I don't like "conversations" because it

What about "channels"? Like TV channel. Discovery Channel shows science related stuff. History Channel shows history related stuff. AMC plays movies. I think that abstraction would make sense to most end-users. 

## Regarding URLs

>if we do database method we could do more user-friendly IDs as well. 
exploreapollo.org/#/moment/oneSmallStep could just be an alias to exploreapollo.org/#/moment/313374

Yep, this is how we should do it. 

### Encoding in URL

>binary toggle to choose active channels.
For an example we can do have channels 2, 6, 7 active in 8 channels, 0110 0010 => 6 2 There are tons of different ways we can encode it (binary to hex?) so it'll have all the information the URL.

I like this, but it might be a bit too much coordination between the API and the client. Let's start out with some predefined URLs that are loaded into the DB explicitly. A user should eventually be able to create a custom channel/moment/room of their own so we might have to use this idea then.

### Timestamps in URL

Instead of `exploreapollo.org/#/moment/aEaad/3d4h20m11s` we should do `exploreapollo.org/#/moment/aEaad?t=3d4h20m11s`.

Just like YouTube. The main reason being: we can perhaps live-update the query parameter as the audio plays. Query parameters can update without upsetting the browser history API. 

Also, I want to keep our options open as far as sub-URLs. There could perhaps be a page `exploreapollo.org/#/moment/aEaad/personnel` that shows a different sub-view that highlights personnel. Just an example. 

### Timestamp format

I like `1d4h20m10s`. It's easy to understand at a glance.

## Regarding Finding Rooms

>It'd be cool if you don't have the same channels active at the time, the timeline will somehow notify you an event is coming up soon. We need to have some way to show the user that if they're listening to specific channels at some time, they might not hear something interesting being said on other channels.

Ooooh ok, I think you are on to something here. And I think I understand more of what you meant by "moments." I was thinking of a "room/channel" being something you sit inside for a long time and just listen passively. I think you are suggesting presenting a stream of moments to the user and having them 

![2015-09-24 19 48 31](https://cloud.githubusercontent.com/assets/2192970/10090545/3f7201b2-62f6-11e5-830b-82fe78fb9c74.jpg)

A user might start at blast off, branch off into slingshot discussion and then end up at the moon landing.

**Comment by JamieCrisman** [comment]
My initial reaction to channels is that we need to ensure we keep our word-usage consistent. In audio, channels can refer to individual tracks. So if we go with channels, we as a team need to be consistent on how we refer to them.

**Comment by austinpray** [comment]
Consolidated the "rooms/channels" vs "moments" discussion here: https://github.com/UTD-CRSS/exploreapollo.org-project-documentation/issues/11
